version: '3.8'

services:
  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: swift-ssh-test-server
    hostname: ssh-test
    ports:
      - "2222:2222"  # SSH端口映射
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PUBLIC_KEY_DIR=/pubkeys #可选
      - SUDO_ACCESS=false #可选
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password123
      - USER_NAME=testuser
    volumes:
      - ./test-data:/config  # 持久化配置
      - ./test-files:/home/testuser/test_files  # 测试文件目录
    restart: unless-stopped
    networks:
      - ssh-test-network

  # 可选：添加一个轻量级的Alpine SSH服务器作为备用
  ssh-alpine:
    image: alpine:latest
    container_name: swift-ssh-alpine-server
    hostname: ssh-alpine
    ports:
      - "2223:22"
    command: |
      sh -c "
        apk add --no-cache openssh openssh-sftp-server &&
        ssh-keygen -A &&
        adduser -D -s /bin/sh testuser &&
        echo 'testuser:password123' | chpasswd &&
        echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
        echo 'PermitRootLogin no' >> /etc/ssh/sshd_config &&
        echo 'Subsystem sftp /usr/lib/ssh/sftp-server' >> /etc/ssh/sshd_config &&
        mkdir -p /home/testuser/test_files &&
        chown testuser:testuser /home/testuser/test_files &&
        /usr/sbin/sshd -D
      "
    networks:
      - ssh-test-network

networks:
  ssh-test-network:
    driver: bridge 